version: '2.3'

services:
  python:
    build:
      context: .
      target: development
    working_dir: ${PWD}
    environment:
      PATH: $PATH:${PWD}/.venv/bin
      PYTHONPATH: ${PWD}/src
    volumes:
      - .:${PWD}
