---
apiVersion: metacontroller.k8s.io/v1alpha1
kind: CompositeController
metadata:
  name: consumer-deployment-controller
spec:
  parentResource:
    apiVersion: mindetic.gt8/v1
    resource: consumer-deployment-controllers
  childResources:
  - apiVersion: v1
    resource: services
    updateStrategy:
      method: InPlace
  - apiVersion: extensions/v1beta1
    resource: replicasets
    updateStrategy:
      method: InPlace
  hooks:
    sync:
      webhook:
        url: http://consumer-deployment-controller.metacontroller/watch
