---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: consumer-deployment-controllers.mindetic.gt8
spec:
  group: mindetic.gt8
  version: v1
  scope: Namespaced
  names:
    plural: consumer-deployment-controllers
    singular: consumer-deployment-controller
    kind: ConsumerDeploymentController
    shortNames:
    - cdc
